version: '3.7'
services:

  ldap-search-api:
    image: devatherock/ldap-search-api:${DOCKER_TAG:-latest}
    container_name: ldap-search-api-intg
    network_mode: "host"
    volumes:
      - ./src/integrationTest/resources/application-docker.yml:/config/application.yml
    environment:
      LOGBACK_CONFIGURATION_FILE: logback-json.xml
      MICRONAUT_CONFIG_FILES: '/config/application.yml'

  health:
    image: alpine:3.21.2
    network_mode: "host"
    depends_on:
      - ldap-search-api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 2s
      timeout: 60s
      retries: 30
    command: |
      sh -c '
        wget -q -O - http://localhost:8080/health
        sleep 120
      '
