version: '3.7'
services:

  ldap-search-api:
    image: devatherock/ldap-search-api:latest
    network_mode: "host"
    environment:
      LDAP_HOST: ldaps://ldap.jumpcloud.com:636
      LDAP_USERNAME: $JUMPCLOUD_USERNAME
      LDAP_PASSWORD: $JUMPCLOUD_PASSWORD
      LDAP_BASE_DN: $JUMPCLOUD_BASE_DN
      LOGBACK_CONFIGURATION_FILE: 'https://raw.githubusercontent.com/devatherock/artifactory-badge/master/src/main/resources/logback.xml'