version: '3.7'
services:

  ldap-search-api:
    image: devatherock/ldap-search-api:${DOCKER_TAG:-latest}
    network_mode: "host"
    environment:
      LDAP_HOST: ldaps://ldap.jumpcloud.com:636
      LDAP_USERNAME: $JUMPCLOUD_USERNAME
      LDAP_PASSWORD: $JUMPCLOUD_PASSWORD
      LDAP_BASE_DN: $JUMPCLOUD_BASE_DN
      LOGBACK_CONFIGURATION_FILE: 'https://raw.githubusercontent.com/devatherock/artifactory-badge/master/src/main/resources/logback.xml'

  health:
    image: alpine:3.20.3
    network_mode: "host"
    depends_on:
      - ldap-search-api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 2s
      timeout: 60s
      retries: 30
    command: |
      sh -c '
        wget -q -O - http://localhost:8080/health
        sleep 120
      '
